Update log

diff --git a/.github/actions/set-bot-callback/action.yml b/.github/actions/set-bot-callback/action.yml
--- a/.github/actions/set-bot-callback/action.yml
+++ b/.github/actions/set-bot-callback/action.yml
@@ -19,8 +19,7 @@ runs:
     id: webhook-curl
     shell: bash
     run: |
-      status-code=$(curl -X "GET" -f -LI "https://api.telegram.org/bot${{ inputs.bot-token }}/setWebhook?url=${{ inputs.callback-url }}/callback" -o /dev/null -w '%{http_code}\n' -s)
-      echo "status-code=$status-code" >> $GITHUB_OUTPUT
-      if [$status-code != 200]; then
-        echo "::error file=set-bo-callback/action.yml,line=21::Request has failed with status code $status-code"
+      statuscode=$(curl -X "GET" -f -LI "https://api.telegram.org/bot${{ inputs.bot-token }}/setWebhook?url=${{ inputs.callback-url }}/callback" -o /dev/null -w '%{http_code}\n' -s)
+      if [$statuscode != 200]; then
+        echo "::error::Filename set-bo-callback/action.yml request was not sucessfull" && exit 1
       fi
